{% set version = "1.4.0" %}

package:
  name: ioos-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ioos_tools/ioos_tools-{{ version }}.tar.gz
  sha256: 0cddd2b7c9d36443bbe98147ac1f66a468dc5d06d742c8b7b0f5c6cbdba0f506

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - cftime
    - folium
    - iris
    - matplotlib
    - netcdf4
    - numpy
    - oceans
    - owslib
    - pandas >=0.20
    - pytz
    - requests
    - retrying
    - scikit-learn
    - scipy
    - timeout-decorator
    - lxml

test:
  imports:
    - ioos_tools

about:
  home: https://github.com/pyoceans/ioos_tools
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for IOOS examples'

extra:
  recipe-maintainers:
    - ocefpaf
