{% set version = "1.3.3" %}

package:
  name: ioos-tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ioos_tools/ioos_tools-{{ version }}.tar.gz
  sha256: 190db4f5e505414c4b51b48f8815efdd5b47cb08631f0889c3ba779ad79d4033

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - beautifulsoup4
    - cftime
    - folium
    - iris
    - matplotlib
    - netcdf4
    - numpy
    - oceans
    - owslib
    - pandas >=0.20
    - pytz
    - requests
    - retrying
    - scikit-learn
    - scipy
    - timeout-decorator

test:
  imports:
    - ioos_tools

about:
  home: https://github.com/pyoceans/ioos_tools
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for IOOS examples'

extra:
  recipe-maintainers:
    - ocefpaf
