{% set version = "1.2.1" %}

package:
  name: ioos_tools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ioos_tools/ioos_tools-{{ version }}.tar.gz
  sha256: 0612fe442a38715a3c2d660d302ac83c0abbe2844adddc0227e9d6942512bb44

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - beautifulsoup4
    - folium
    - iris
    - matplotlib
    - netcdf4
    - cftime
    - numpy
    - oceans
    - owslib
    - pandas
    - pytz
    - requests
    - scikit-learn
    - scipy
    - timeout-decorator

test:
  imports:
    - ioos_tools

about:
  home: https://github.com/pyoceans/ioos_tools
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Misc functions for IOOS notebooks'

extra:
  recipe-maintainers:
    - ocefpaf
