travis:
  secure:
    BINSTAR_TOKEN: Iq+lUq4tAaCdrntgqpertLsWw+H8UvjVDtKGIfL+dPG9oeQhydoJWyAGc8YcExI64HFveApTjYQvjUEZT/XbpPZoeM1CrpvEXb8u6cDa6Fpx45YfoRZthKzEmKZh/YGlf1xh9m6tTDFjalbpwaPk88q3MmKJCGdJhwEHSdBhfGodI0Fk0NyrWnyy9xhQujpmzVVc7Rd5FMUaMvLISbnTN1AXTcVx+BMm1vkiJh5lhHxwZNW5Hsh54zxz/sAcBLSsUJ45OTgTHWCvlRCpgEXrei21yZQM2GIOfhQxQFL+x1ZFmGyjoRK6LwDXD9Lp0hf8+kbJ/9toAApYovKh+oMF1OJuNHjJzl2SY0GGR4tt/OS8vhncqRVvaLDcp52HTWKFJ+R3oCZDYHt+bZZVEscEG2I8fTQUnBZKr9pigWcPC/u1D1rKbTTSoQlMwZ83gfA6GQ4ETdo+UMyv3LuApOPSHI+wk1tF4bOVyU9Bs7jfqRbcPfGeYk/hyYZnBgzuAwjN5Jd2wJQT82X6ai/ZDZ/XSpNF2RovA7gSd1Ldf/9gDYLTFxO+MWCN5RWD7YJN/xgy5x4oY+dFDgyqoO6J4Ros8MUpaC3eo3JrzykBkbUgvqsbPHSJAelwwZIFQC9TtIa2wUiVo/MlyRVA8Byv0vlXefJmuUQGocEe9D3jsNgsAUc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
